In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df=pd.read_csv("/content/madfhantr.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
df.shape

(614, 13)

In [1]:
# Fill missing numerical values with the mean
df["LoanAmount"].fillna(df["LoanAmount"].mean(), inplace=True)
df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].mean(), inplace=True)
df["Credit_History"].fillna(df["Credit_History"].mean(), inplace=True)

# Fill missing categorical values with the most frequent category (mode)
categories = ["Gender", "Married", "Dependents", "Self_Employed"]
for col in categories:
    df[col].fillna(df[col].mode().values[0],inplace=True)

# Check for missing values after filling
print(df.isnull().sum())

NameError: name 'df' is not defined

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder=LabelEncoder()
df['Gender']=label_encoder.fit_transform(df['Gender'])
df['Married']=label_encoder.fit_transform(df['Married'])
df['Self_Employed']=label_encoder.fit_transform(df['Self_Employed'])
df['Education']=label_encoder.fit_transform(df['Education'])
df['Property_Area']=label_encoder.fit_transform(df['Property_Area'])
df['Loan_Status']=label_encoder.fit_transform(df['Loan_Status'])
df['Loan_ID']=label_encoder.fit_transform(df['Loan_ID'])
df['Dependents']=label_encoder.fit_transform(df['Dependents'])
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,1,0,0,0,0,5849,0.0,146.412162,360.0,1.0,2,1
1,1,1,1,1,0,0,4583,1508.0,128.000000,360.0,1.0,0,0
2,2,1,1,0,0,1,3000,0.0,66.000000,360.0,1.0,2,1
3,3,1,1,0,1,0,2583,2358.0,120.000000,360.0,1.0,2,1
4,4,1,0,0,0,0,6000,0.0,141.000000,360.0,1.0,2,1

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score,recall_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

x=df.drop(columns=['Loan_ID','Loan_Status'])
y=df['Loan_Status']

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=DecisionTreeClassifier(random_state=42)
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)
print("Confusion Matrix: ", confusion_matrix(Y_test, y_pred))
print ("Accuracy : ", accuracy_score(Y_test,y_pred)*100)
print("Report : ", classification_report(Y_test, y_pred))
print("f1_score: ", f1_score(Y_test, y_pred))
print ("recall_score : ", recall_score(Y_test,y_pred))

Confusion Matrix:  [[23 20]
 [15 65]]
Accuracy :  71.54471544715447
Report :                precision    recall  f1-score   support

           0       0.61      0.53      0.57        43
           1       0.76      0.81      0.79        80

    accuracy                           0.72       123
   macro avg       0.68      0.67      0.68       123
weighted avg       0.71      0.72      0.71       123

f1_score:  0.7878787878787878
recall_score :  0.8125